package com.fieldsentinel

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.io.File
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import java.nio.ByteBuffer

class EmbeddingStore(private val context: Context) {

    companion object {
        private const val KEY_ALIAS    = "FieldSentinelEmbeddingKey"
        private const val KEYSTORE     = "AndroidKeyStore"
        private const val ALGORITHM    = KeyProperties.KEY_ALGORITHM_AES
        private const val BLOCK_MODE   = KeyProperties.BLOCK_MODE_GCM
        private const val PADDING      = KeyProperties.ENCRYPTION_PADDING_NONE
        private const val TRANSFORM    = "AES/GCM/NoPadding"
        private const val IV_SIZE      = 12   // bytes
        private const val TAG_SIZE     = 128  // bits
    }

    init {
        createKeyIfNotExists()
    }

    // Creates AES-256 key inside Android Keystore hardware if it doesn't exist
    private fun createKeyIfNotExists() {
        val keyStore = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        if (keyStore.containsAlias(KEY_ALIAS)) return

        val keyGenerator = KeyGenerator.getInstance(ALGORITHM, KEYSTORE)
        keyGenerator.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
            .setBlockModes(BLOCK_MODE)
            .setEncryptionPaddings(PADDING)
            .setKeySize(256)
            .build()
        )
        keyGenerator.generateKey()
    }

    private fun getKey(): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE).apply { load(null) }
        return keyStore.getKey(KEY_ALIAS, null) as SecretKey
    }

    // Save embedding: converts float array → bytes → encrypts → writes to file
    fun saveEmbedding(employeeId: String, embedding: FloatArray) {
        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(Cipher.ENCRYPT_MODE, getKey())

        val iv           = cipher.iv   // 12 random bytes generated by cipher
        val embeddingBytes = floatArrayToBytes(embedding)
        val encrypted    = cipher.doFinal(embeddingBytes)

        // Store as: IV (12 bytes) + ciphertext
        val file = getEmbeddingFile(employeeId)
        file.writeBytes(iv + encrypted)
    }

    // Load and decrypt embedding from file
    fun loadEmbedding(employeeId: String): FloatArray? {
        val file = getEmbeddingFile(employeeId)
        if (!file.exists()) return null

        val data       = file.readBytes()
        val iv         = data.sliceArray(0 until IV_SIZE)
        val ciphertext = data.sliceArray(IV_SIZE until data.size)

        val cipher = Cipher.getInstance(TRANSFORM)
        cipher.init(Cipher.DECRYPT_MODE, getKey(), GCMParameterSpec(TAG_SIZE, iv))

        val decrypted = cipher.doFinal(ciphertext)
        return bytesToFloatArray(decrypted)
    }

    fun hasEnrollment(employeeId: String): Boolean {
        return getEmbeddingFile(employeeId).exists()
    }

    private fun getEmbeddingFile(employeeId: String): File {
        return File(context.filesDir, "enrollment_${employeeId}.enc")
    }

    // Convert FloatArray to ByteArray (each float = 4 bytes)
    private fun floatArrayToBytes(floats: FloatArray): ByteArray {
        val buffer = ByteBuffer.allocate(floats.size * 4)
        floats.forEach { buffer.putFloat(it) }
        return buffer.array()
    }

    // Convert ByteArray back to FloatArray
    private fun bytesToFloatArray(bytes: ByteArray): FloatArray {
        val buffer = ByteBuffer.wrap(bytes)
        return FloatArray(bytes.size / 4) { buffer.float }
    }
}